### ISSUE TITLE
File size exceeded the configured limit of 20 MB.

### ISSUE THREAD

**Issue by gitGalu** [arianrhodsandlot/retroarch-emscripten-build#2]
Hi, I'm not sure if this should be reported but some of the files fail to download ("File size exceeded the configured limit of 20 MB."), e.g.: https://cdn.jsdelivr.net/gh/arianrhodsandlot/retroarch-emscripten-build@v1.19.1/retroarch/mame2003_plus_libretro.wasm

**Comment by arianrhodsandlot** [comment]
Good catch:) I think here's the right place to report it but frankly I cannot fix this directly. I just raised an issue here https://github.com/jsdelivr/jsdelivr/issues/18609 and hope the proposal will be approved.

**Comment by arianrhodsandlot** [comment]
It seems that all cores can be loaded now 🥳.
